version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./cron:/app/cron
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  cron:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./cron:/app/cron
    env_file:
      - backend/.env
    entrypoint: ["bash", "-c", "cron && tail -f /var/log/cron.log"]
