services:
  - type: web
    name: chaturai-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GNEWS_API_KEY
        sync: false
    plan: free
